---
title: Maak een raster met CSS
hero_image: images/banner.png
description: Gebruik de CSS-weergave-eigenschap om een raster te maken
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Maak een raster met CSS
