title: css-display-grid
hero_image: images/banner.png
description: Use the CSS display property to create a grid
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Create a grid with CSS
