title: Créer une grille avec CSS
hero_image: images/banner.png
description: Utilise la propriété d'affichage CSS pour créer une grille
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Créer une grille avec CSS
